---
- name: Check if /tmp/.bench exists
  stat:
    path: /tmp/.bench
  register: tmp_bench

- name: Check if bench_repo_path exists
  stat:
    path: "{{ bench_repo_path }}"
  register: bench_repo_register

- name: move /tmp/.bench if it exists
  command: "cp -R /tmp/.bench {{ bench_repo_path }}"
  when: tmp_aksara.stat.exists and not bench_repo_register.stat.exists

- name: install bench
  pip:
    name: "{{ bench_repo_path }}"
    extra_args: "-e"
  become: yes
  become_user: root

- name: Overwrite bench if required
  file:
    state: absent
    path: "{{ aksara_path }}"
  when: overwrite

- name: Check whether bench exists
  stat:
    path: "{{ aksara_path }}"
  register: bench_stat

- name: Fix permissions
  become_user: root
  command: chown {{ logica_user }} -R {{ user_directory }}

- name: python3 bench init for develop
  command: bench init {{ aksara_path }} --logica-path {{ logica_repo_url }} --logica-branch {{ logica_branch }} --python {{ python }}
  args:
    creates: "{{ aksara_path }}"
  when: not bench_stat.stat.exists and not production

- name: python3 bench init for production
  command: bench init {{ aksara_path }} --logica-path {{ logica_repo_url }} --logica-branch {{ logica_branch }} --python {{ python }}
  args:
    creates: "{{ aksara_path }}"
  when: not bench_stat.stat.exists and production

# setup common_site_config
- name: setup config
  command: bench setup config
  args:
    creates: "{{ aksara_path }}/sites/common_site_config.json"
    chdir: "{{ aksara_path }}"

- include_tasks: setup_inputrc.yml

# Setup Procfile
- name: Setup Procfile
  command: bench setup procfile
  args:
    creates: "{{ aksara_path }}/Procfile"
    chdir: "{{ aksara_path }}"

# Setup Redis env for RQ
- name: Setup Redis
  command: bench setup redis
  args:
    creates: "{{ aksara_path }}/config/redis_socketio.conf"
    chdir: "{{ aksara_path }}"

# Setup an ERPNext site
- include_tasks: setup_erpnext.yml
  when: not run_travis

# Setup Bench for production environment
- include_tasks: setup_bench_production.yml
  vars:
    aksara_path: "{{ user_directory }}/{{ bench_name }}"
  when: not run_travis and production
