---
- name: Check if ERPNext App exists
  stat: path="{{ aksara_path }}/apps/erpnext"
  register: app

- name: Get the ERPNext app
  command: bench get-app erpnext {{ erpnext_repo_url }} --branch {{ erpnext_branch }}
  args:
    creates: "{{ aksara_path }}/apps/erpnext"
    chdir: "{{ aksara_path }}"
  when: not app.stat.exists and not without_erpnext

- name: Check whether the site already exists
  stat: path="{{ aksara_path }}/sites/{{ site }}"
  register: site_folder
  when: not without_site

- name: Create a new site
  command: "bench new-site {{ site }} --admin-password '{{ admin_password }}' --mariadb-root-password '{{ mysql_root_password }}'"
  args:
    chdir: "{{ aksara_path }}"
  when: not without_site and not site_folder.stat.exists

- name: Install ERPNext to default site
  command: "bench --site {{ site }} install-app erpnext"
  args:
    chdir: "{{ aksara_path }}"
  when: not without_site and not without_erpnext
